# Generated by Django 3.2.7 on 2021-10-04 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('management_address', models.GenericIPAddressField()),
                ('device_role', models.CharField(choices=[('access', 'access'), ('distribution', 'distribution'), ('core', 'core'), ('edge', 'edge')], max_length=20)),
                ('in_production', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('recommended_os_version', models.CharField(max_length=50)),
                ('capabilities', models.CharField(max_length=200)),
                ('number_of_interfaces', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('vlan_tag', models.PositiveIntegerField()),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networks', to='api.device')),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('connected_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.interface')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='api.device')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='hardware_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='api.hardware'),
        ),
    ]
